/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import logic.ManipuladorStrings;

/**
 *
 * @author crist
 */
public class ManipularStrings extends javax.swing.JFrame {

    ManipuladorStrings manipulador;

    /**
     * Creates new form ManipularStrings
     */
    public ManipularStrings() {
        manipulador = new ManipuladorStrings();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        outputInverter = new javax.swing.JTextField();
        btnInverter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        outputTamanho = new javax.swing.JTextField();
        btnTamanho = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        outputPalindromo = new javax.swing.JTextField();
        btnPalindromo = new javax.swing.JButton();
        outputVogais = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnVogais = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        outputConsoantes = new javax.swing.JTextField();
        btnConsoantes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        outputCriptografar = new javax.swing.JTextField();
        btnCriptografar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        outputDescriptografar = new javax.swing.JTextField();
        btnDescriptografar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(19, 15, 64));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 225, 225));
        jLabel1.setText("MANIPULADOR DE STRINGS");

        jSeparator1.setBackground(new java.awt.Color(225, 225, 225));
        jSeparator1.setForeground(new java.awt.Color(225, 225, 225));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inverter");

        outputInverter.setEditable(false);
        outputInverter.setBackground(new java.awt.Color(19, 17, 34));
        outputInverter.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        outputInverter.setForeground(new java.awt.Color(255, 255, 255));

        btnInverter.setBackground(new java.awt.Color(19, 17, 34));
        btnInverter.setForeground(new java.awt.Color(225, 225, 225));
        btnInverter.setText("OK");
        btnInverter.setEnabled(false);
        btnInverter.setOpaque(true);
        btnInverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInverterActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tamanho");

        outputTamanho.setEditable(false);
        outputTamanho.setBackground(new java.awt.Color(19, 17, 34));
        outputTamanho.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        outputTamanho.setForeground(new java.awt.Color(255, 255, 255));

        btnTamanho.setBackground(new java.awt.Color(19, 17, 34));
        btnTamanho.setForeground(new java.awt.Color(225, 225, 225));
        btnTamanho.setText("OK");
        btnTamanho.setEnabled(false);
        btnTamanho.setOpaque(true);
        btnTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamanhoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Palíndromo");

        outputPalindromo.setEditable(false);
        outputPalindromo.setBackground(new java.awt.Color(19, 17, 34));
        outputPalindromo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        outputPalindromo.setForeground(new java.awt.Color(255, 255, 255));

        btnPalindromo.setBackground(new java.awt.Color(19, 17, 34));
        btnPalindromo.setForeground(new java.awt.Color(225, 225, 225));
        btnPalindromo.setText("OK");
        btnPalindromo.setEnabled(false);
        btnPalindromo.setOpaque(true);
        btnPalindromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalindromoActionPerformed(evt);
            }
        });

        outputVogais.setEditable(false);
        outputVogais.setBackground(new java.awt.Color(19, 17, 34));
        outputVogais.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        outputVogais.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vogais");

        btnVogais.setBackground(new java.awt.Color(19, 17, 34));
        btnVogais.setForeground(new java.awt.Color(225, 225, 225));
        btnVogais.setText("OK");
        btnVogais.setEnabled(false);
        btnVogais.setOpaque(true);
        btnVogais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVogaisActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Consoantes");

        outputConsoantes.setEditable(false);
        outputConsoantes.setBackground(new java.awt.Color(19, 17, 34));
        outputConsoantes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        outputConsoantes.setForeground(new java.awt.Color(255, 255, 255));

        btnConsoantes.setBackground(new java.awt.Color(19, 17, 34));
        btnConsoantes.setForeground(new java.awt.Color(225, 225, 225));
        btnConsoantes.setText("OK");
        btnConsoantes.setEnabled(false);
        btnConsoantes.setOpaque(true);
        btnConsoantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsoantesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Criptografar");

        outputCriptografar.setEditable(false);
        outputCriptografar.setBackground(new java.awt.Color(19, 17, 34));
        outputCriptografar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        outputCriptografar.setForeground(new java.awt.Color(255, 255, 255));

        btnCriptografar.setBackground(new java.awt.Color(19, 17, 34));
        btnCriptografar.setForeground(new java.awt.Color(225, 225, 225));
        btnCriptografar.setText("OK");
        btnCriptografar.setEnabled(false);
        btnCriptografar.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descriptografar");

        outputDescriptografar.setEditable(false);
        outputDescriptografar.setBackground(new java.awt.Color(19, 17, 34));
        outputDescriptografar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        outputDescriptografar.setForeground(new java.awt.Color(255, 255, 255));

        btnDescriptografar.setBackground(new java.awt.Color(19, 17, 34));
        btnDescriptografar.setForeground(new java.awt.Color(225, 225, 225));
        btnDescriptografar.setText("OK");
        btnDescriptografar.setEnabled(false);
        btnDescriptografar.setOpaque(true);
        btnDescriptografar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescriptografarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Entrada");

        input.setBackground(new java.awt.Color(19, 17, 34));
        input.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        input.setForeground(new java.awt.Color(255, 255, 255));

        btnEnviar.setBackground(new java.awt.Color(19, 17, 34));
        btnEnviar.setForeground(new java.awt.Color(225, 225, 225));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(outputInverter)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnInverter, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(202, 202, 202))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(outputTamanho)
                                            .addComponent(outputPalindromo)
                                            .addComponent(outputVogais, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(outputConsoantes)
                                            .addComponent(outputCriptografar)
                                            .addComponent(outputDescriptografar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnConsoantes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnVogais, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnCriptografar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnDescriptografar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(202, 202, 202))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnTamanho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPalindromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(202, 202, 202))))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnEnviar)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(192, 192, 192)
                                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(0, 8, Short.MAX_VALUE))))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1)))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputInverter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInverter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTamanho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputPalindromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPalindromo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputVogais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVogais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputConsoantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsoantes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputCriptografar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCriptografar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputDescriptografar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDescriptografar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnviar)
                        .addGap(171, 171, 171))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (input.getText().length() >= 1) {
            if (input.getText().matches("[0-9]*")) {
                JOptionPane.showMessageDialog(this, "Formato inválido", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            } else {
                manipulador.setEntradaOriginal(input.getText());
                btnInverter.setEnabled(rootPaneCheckingEnabled);
                btnTamanho.setEnabled(rootPaneCheckingEnabled);
                btnVogais.setEnabled(rootPaneCheckingEnabled);
                btnConsoantes.setEnabled(rootPaneCheckingEnabled);
                btnCriptografar.setEnabled(rootPaneCheckingEnabled);
                btnDescriptografar.setEnabled(rootPaneCheckingEnabled);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Entrada vazia, digite algo", "Entrada inválida", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnInverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInverterActionPerformed
        manipulador.inverter();
        outputInverter.setText(manipulador.getSaidaInverter());
        btnPalindromo.setEnabled(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnInverterActionPerformed

    private void btnTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamanhoActionPerformed
        manipulador.tamanho();
        outputTamanho.setText(String.valueOf(manipulador.getSaidaTamanho()));
    }//GEN-LAST:event_btnTamanhoActionPerformed

    private void btnPalindromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalindromoActionPerformed
        manipulador.palindromo();
        outputPalindromo.setText(String.valueOf(manipulador.isSaidaPalindromo()));
    }//GEN-LAST:event_btnPalindromoActionPerformed

    private void btnVogaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVogaisActionPerformed
        manipulador.vogais();
        outputVogais.setText(String.valueOf(manipulador.getSaidaVogais()));
    }//GEN-LAST:event_btnVogaisActionPerformed

    private void btnConsoantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsoantesActionPerformed
        manipulador.consoantes();
        outputConsoantes.setText(String.valueOf(manipulador.getSaidaConsoantes()));
    }//GEN-LAST:event_btnConsoantesActionPerformed

    private void btnDescriptografarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescriptografarActionPerformed
        
    }//GEN-LAST:event_btnDescriptografarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManipuladorStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManipuladorStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManipuladorStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManipuladorStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManipularStrings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsoantes;
    private javax.swing.JButton btnCriptografar;
    private javax.swing.JButton btnDescriptografar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnInverter;
    private javax.swing.JButton btnPalindromo;
    private javax.swing.JButton btnTamanho;
    private javax.swing.JButton btnVogais;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField outputConsoantes;
    private javax.swing.JTextField outputCriptografar;
    private javax.swing.JTextField outputDescriptografar;
    private javax.swing.JTextField outputInverter;
    private javax.swing.JTextField outputPalindromo;
    private javax.swing.JTextField outputTamanho;
    private javax.swing.JTextField outputVogais;
    // End of variables declaration//GEN-END:variables
}
